### ISSUE TITLE
[BUG] Cannot delete accounts

### ISSUE THREAD

**Issue by jodri-code** [Common-Codes/crispy#8]
Pressing the delete account button on [Crispy:main](https://crispychat.tech/app/#account) - nothing happens.
I believe I may have structured the `.then` function incorrectly.
Live testing sucks.

**Comment by TallerThanShort** [comment]
Backend does allow authors with matching uid to delete their matching account details.
I believe it probably is the `.then` function...

**Comment by TallerThanShort** [comment]
Turns out that user's cred value is either volatile or accessed another way to how you are trying to do

**Comment by TallerThanShort** [comment]
btw forgor to mention [fixed](https://github.com/Common-Codes/crispy/commit/c6e6bd23ea3bf519c1527154b8ba49605a860cd5)
